name: Weekly Scheduled Action

on:
  schedule:
    # Runs at 00:00 UTC every Saturday
    - cron: '*/5 * * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test1
      - name: Debug information
        run: |
          echo "Current ref: ${{ github.ref }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow triggered at: $(date)"
          git branch --show-current
      - name: Run test1 branch job
        run: echo "Running on test1 branch"
  